[package]
name = "shell"
version = "0.1.0"
edition.workspace = true
authors = ["The prefix-dev/shell team <hi@prefix.dev>"]
description = "A cross-platform, bash compatible shell"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
default-run = "shell"
publish = false

[lib]
name = "shell"
path = "src/lib.rs"

[[bin]]
name = "shell"
path = "src/main.rs"

[features]

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
deno_task_shell = { path = "../deno_task_shell", features = ["shell"] }
futures = "0.3.33"
rustyline = { version = "18.0.1", features = ["derive"] }
tokio = "1.53.1"
uu_ls = "0.10.0"
dirs = "6.0.0"
which = "8.0.5"
uu_uname = "0.10.0"
uu_touch = "0.10.0"
uu_date = "0.10.0"
miette = { version = "7.6.0", features = ["fancy"] }
filetime = "0.2.29"
chrono = "0.4.45"
jiff = "0.2.35"
parse_datetime = "0.15.0"
dtparse = "2.0.1"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Threading"] }
ctrlc = "3.5.2"
libc = "0.2.189"

[dev-dependencies]
tempfile = "3.27.0"

[package.metadata.release]
# Dont publish the binary
release = false
